---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: debian/jessie64
  driver_config:
    network:
      - ["forwarded_port", {guest: 80, host: 8080}]
      - ["forwarded_port", {guest: 8125, host: 8125}]

suites:
  - name: linux
    run_list:
      - recipe[grafana-graphite-server::default]
